/*
Liban Guled
Iconic Tech Database
*/
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "sqlite3.h"

int main(int argc, char ** argv) {
  // Declare variables to hold the database connection and prepared statement
  sqlite3 * db;
  sqlite3_stmt * stmt;
  int rc;

  // Open the database connection
  rc = sqlite3_open("IconicTech.db", & db);

  // Check if the connection was successful
  if (rc != SQLITE_OK) {
    printf("Failed to open database: %s\n", sqlite3_errmsg(db));
    return 1;
  }

  // Display the main menu
  while (1) {
    printf("\nWelcome to the Iconic Tech Application:\n");
    printf("0) Exit\n");
    printf("1) What is The Total Sales?\n");
    printf("2) Which Technician Fixed the Most Devices?\n");
    printf("3) Show The Profits Generated by the Cashier\n");
    printf("4) Which Customer Came To Our Store The Most?\n");
    printf("5) What is the Total Profit on October 1, 2022? \n");
    printf("6) What is the Total Customers that shopped in October?\n");
    printf("7) What is the Most Expensive Product?\n");
    printf("8) Which Employees Don't Fix Devices?\n");
    printf("9) Show Customers With an Email\n");
    printf("10) Show all the iPhone Products and Services\n");

    // Prompt the user to enter their choice
    printf("Enter your choice: ");
    int choice;
    scanf("%d", & choice);

    // Check if the user chose to exit the program
    if (choice == 0) {
      // Exit the program
      break;
    } 
    
    else if (choice == 1) {

      // Query1: What is the Total Sales?
      printf("\n----------------------------\n");

      // Define the SQL query to find the total sales
      const char * sql1 = "SELECT SUM(Price) AS 'Total Sales' FROM Offer;";

      // Prepare the SQL statement
      rc = sqlite3_prepare_v2(db, sql1, -1, & stmt, NULL);

      // Check if the statement was prepared successfully
      if (rc != SQLITE_OK) {
        printf("Failed to prepare statement: %s\n", sqlite3_errmsg(db));
        return 1;
      }

      // Execute the SQL statement and loop through the results
      while ((rc = sqlite3_step(stmt)) == SQLITE_ROW) {
        int totalSales = sqlite3_column_int(stmt, 0);
        printf("Total sales: $%d\n", totalSales);
      }
      printf("----------------------------\n");

      // Finalize the prepared statement
      sqlite3_finalize(stmt);
    } 
    
    else if (choice == 2) {
      // Query2: Find the employee that fixed the most devices
      printf("\n----------------------------\n");

      const char * sql2 = "SELECT Employee.FirstName || ' ' || Employee.LastName AS EmployeeName, "
                          "COUNT(EmployeeDoesService.EmployeeId) AS DevicesFixed "
                          "FROM EmployeeDoesService "
                          "JOIN Employee ON EmployeeDoesService.EmployeeId = Employee.Id  "
                          "GROUP BY EmployeeDoesService.EmployeeId   "
                          "ORDER BY DevicesFixed DESC  "
                          "LIMIT 1;";

      rc = sqlite3_prepare_v2(db, sql2, -1, & stmt, NULL);
      if (rc != SQLITE_OK) {
        printf("Failed to prepare statement: %s\n", sqlite3_errmsg(db));
        return 1;
      }

      // Execute the SQL statement and loop through the results
      while ((rc = sqlite3_step(stmt)) == SQLITE_ROW) {
        const char * name = (const char * ) sqlite3_column_text(stmt, 0);
        int count = sqlite3_column_int(stmt, 1);
        printf("Technician %s fixed %d devices\n", name, count);
      }

      printf("----------------------------\n");

      sqlite3_finalize(stmt);
    } 
    
    else if (choice == 3) {
      // Query3: Show Employee’s Total Profit
      printf("\n--------------------------------------------------------------------------\n");

      const char * sql3 = "SELECT Employee.FirstName || ' ' || Employee.LastName AS EmployeeName, SUM(Offer.Price - Offer.Cost) AS TotalProfit "
                          "FROM Offer "
                          "INNER JOIN StoreTransaction ON Offer.Id = StoreTransaction.OfferId "
                          "INNER JOIN Employee ON Employee.Id = StoreTransaction.EmployeeId "
                          "GROUP BY EmployeeName;";

      rc = sqlite3_prepare_v2(db, sql3, -1, & stmt, NULL);
      if (rc != SQLITE_OK) {
        printf("Failed to prepare statement: %s\n", sqlite3_errmsg(db));
        return 1;
      }

      while ((rc = sqlite3_step(stmt)) == SQLITE_ROW) {
        const char * name = (const char * ) sqlite3_column_text(stmt, 0);
        int profit = sqlite3_column_int(stmt, 1);
        printf("Salesperson %s generated a total profit of $%d for the store\n", name, profit);
      }

      printf("--------------------------------------------------------------------------\n");

      sqlite3_finalize(stmt);
    } 
    
    else if (choice == 4) {
      // Query4: Find the customer that shops the most
      printf("\n--------------------------------------\n");

      const char * sql4 = "SELECT StoreTransaction.CustomerId, Customer.FirstName || ' ' || Customer.LastName as FullName, COUNT(*) as TimesShopped "
                          "FROM StoreTransaction "
                          "JOIN Customer ON Customer.Id = StoreTransaction.CustomerId "
                          "GROUP BY StoreTransaction.CustomerId "
                          "ORDER BY TimesShopped DESC "
                          "LIMIT 1;";

      rc = sqlite3_prepare_v2(db, sql4, -1, & stmt, NULL);
      if (rc != SQLITE_OK) {
        printf("Failed to prepare statement: %s\n", sqlite3_errmsg(db));
        return 1;
      }

      while ((rc = sqlite3_step(stmt)) == SQLITE_ROW) {
        const char * name = (const char * ) sqlite3_column_text(stmt, 1);
        int count = sqlite3_column_int(stmt, 2);
        printf("Customer %s has shopped %d times\n", name, count);
      }

      printf("--------------------------------------\n");

      sqlite3_finalize(stmt);
    } 
    
    else if (choice == 5) {
      // Query5: Find the total profit on October 1, 2022
      printf("\n----------------------------------------\n");

      const char * sql5 = "SELECT SUM(o.Price - o.Cost) AS 'Total Profit' "
                          "FROM Offer o "
                          "JOIN StoreTransaction t ON t.OfferId = o.Id "
                          "WHERE t.Day = 1 AND t.Month = 10 AND t.Year = 2022;";

      rc = sqlite3_prepare_v2(db, sql5, -1, & stmt, NULL);
      if (rc != SQLITE_OK) {
        printf("Failed to prepare statement: %s\n", sqlite3_errmsg(db));
        return 1;
      }

      while ((rc = sqlite3_step(stmt)) == SQLITE_ROW) {
        int totalProfit = sqlite3_column_int(stmt, 0);
        printf("Total Profit on October 1st, 2022: $%d\n", totalProfit);
      }
      printf("----------------------------------------\n");

      sqlite3_finalize(stmt);
    } 
    
    else if (choice == 6) {
      // Query6: Find the total number of customers that shopped in October
      printf("\n-------------------------------\n");

      const char * sql6 = "SELECT COUNT(DISTINCT CustomerId) AS 'Total Customers This Month' "
                          "FROM StoreTransaction "
                          "WHERE Month = 10;";

      rc = sqlite3_prepare_v2(db, sql6, -1, & stmt, NULL);
      if (rc != SQLITE_OK) {
        printf("Failed to prepare statement: %s\n", sqlite3_errmsg(db));
        return 1;
      }

      while ((rc = sqlite3_step(stmt)) == SQLITE_ROW) {
        int totalCustomers = sqlite3_column_int(stmt, 0);
        printf("Total customers this month: %d\n", totalCustomers);
      }
      printf("-------------------------------\n");

      sqlite3_finalize(stmt);
    } 
    
    else if (choice == 7) {
      // Query7: Find the most expensive product
      printf("\n-------------------------------------------------\n");

      const char * sql7 = "SELECT Name, Price "
                          "FROM Offer "
                          "ORDER BY Price DESC "
                          "LIMIT 1;";

      rc = sqlite3_prepare_v2(db, sql7, -1, & stmt, NULL);
      if (rc != SQLITE_OK) {
        printf("Failed to prepare statement: %s\n", sqlite3_errmsg(db));
        return 1;
      }

      while ((rc = sqlite3_step(stmt)) == SQLITE_ROW) {
        const char * name = (const char * ) sqlite3_column_text(stmt, 0);
        int price = sqlite3_column_int(stmt, 1);
        printf("Most expensive product: %s, $%d\n", name, price);
      }
      printf("-------------------------------------------------\n");

      sqlite3_finalize(stmt);
    } 
    
    else if (choice == 8) {
      // Query8: Find employees that never did a service task
      printf("\n------------------------------------------------\n");

      const char * sql8 = "SELECT e.FirstName || ' ' || e.LastName AS 'Employees That Never Did a Service Task' "
                          "FROM Employee e "
                          "LEFT JOIN EmployeeDoesService eds ON eds.EmployeeId = e.Id "
                          "WHERE eds.EmployeeId IS NULL;";

      rc = sqlite3_prepare_v2(db, sql8, -1, & stmt, NULL);
      if (rc != SQLITE_OK) {
        printf("Failed to prepare statement: %s\n", sqlite3_errmsg(db));
        return 1;
      }

      while ((rc = sqlite3_step(stmt)) == SQLITE_ROW) {
        const char * name = (const char * ) sqlite3_column_text(stmt, 0);
        printf("Employees that never did a service task: %s\n", name);
      }
      printf("------------------------------------------------\n");

      sqlite3_finalize(stmt);
    } 
    
    else if (choice == 9) {
      // Query9: Show customers with an email
      printf("\n----------------------------\n");

      const char * sql9 = "SELECT FirstName || ' ' || LastName AS 'Full Name', Email "
                          "FROM Customer "
                          "WHERE Email IS NOT NULL;";

      rc = sqlite3_prepare_v2(db, sql9, -1, & stmt, NULL);
      if (rc != SQLITE_OK) {
        printf("Failed to prepare statement: %s\n", sqlite3_errmsg(db));
        return 1;
      }

      while ((rc = sqlite3_step(stmt)) == SQLITE_ROW) {
        const char * name = (const char * ) sqlite3_column_text(stmt, 0);
        const char * email = (const char * ) sqlite3_column_text(stmt, 1);
        printf("%s: %s\n", name, email);
      }
      printf("----------------------------\n");

      sqlite3_finalize(stmt);
    } 
    
    else if (choice == 10) {
      // Query10: Show all the iPhone products and services
      printf("\n----------------------------------------------\n");

      const char * sql10 = "SELECT * FROM Offer WHERE Name LIKE '%iphone%';";

      rc = sqlite3_prepare_v2(db, sql10, -1, & stmt, NULL);
      if (rc != SQLITE_OK) {
        printf("Failed to prepare statement: %s\n", sqlite3_errmsg(db));
        return 1;
      }

      printf("\nId     Name                  Price    Cost\n");
      printf("----------------------------------------------\n");
      while ((rc = sqlite3_step(stmt)) == SQLITE_ROW) {
        int id = sqlite3_column_int(stmt, 0);
        const char * name = (const char * ) sqlite3_column_text(stmt, 1);
        int price = sqlite3_column_int(stmt, 2);
        int cost = sqlite3_column_int(stmt, 3);
        printf("%-4d | %-20s | %-6d | %-6d\n", id, name, price, cost);
      }
      printf("----------------------------------------------\n");

      sqlite3_finalize(stmt);
    }

  }

  sqlite3_close(db);

  return 0;
}