import configparser
import mysql.connector

# Read the configuration file
config = configparser.ConfigParser()
config.read("config.ini")

# Get the MySQL connection details from the configuration file
mysql_config = config["mysql"]

# Open a connection to the database
db = mysql.connector.connect(
    host=mysql_config["host"],
    user=mysql_config["user"],
    password=mysql_config["password"],
    database=mysql_config["database"]
)

# Create a cursor to execute queries
cursor = db.cursor()

# Display the main menu
while True:
    print("\nWelcome to the Iconic Tech Application:")
    print("0) Exit")
    print("1) What is The Total Sales?")
    print("2) Which Technician Fixed the Most Devices?")
    print("3) Show The Profits Generated by the Cashier")
    print("4) Which Customer Came To Our Store The Most?")
    print("5) What is the Total Profit on October 1, 2022?")
    print("6) What is the Total Customers that shopped in October?")
    print("7) What is the Most Expensive Product?")
    print("8) Which Employees Don't Fix Devices?")
    print("9) Show Customers With an Email")
    print("10) Show all the iPhone Products and Services")

    # Prompt the user to enter their choice
    choice = int(input("Enter your choice: "))

    # Check if the user chose to exit the program
    if choice == 0:
        # Exit the program
        break
    elif choice == 1:
        # Query1: What is the Total Sales?
        print("\n----------------------------")

        # Define the SQL query to find the total sales
        sql = "SELECT SUM(Price) AS 'Total Sales' FROM Offer;"

        # Execute the SQL statement
        cursor.execute(sql)

        # Loop through the results
        for (total_sales,) in cursor:
            print(f"Total sales: ${total_sales}")
        print("----------------------------")
    elif choice == 2:
        # Query2: Find the employee that fixed the most devices
        print("\n----------------------------")

        sql = "SELECT CONCAT(Employee.FirstName, ' ', Employee.LastName) AS EmployeeName, "\
              "COUNT(EmployeeDoesService.EmployeeId) AS DevicesFixed "\
              "FROM EmployeeDoesService "\
              "JOIN Employee ON EmployeeDoesService.EmployeeId = Employee.Id  "\
              "GROUP BY EmployeeDoesService.EmployeeId   "\
              "ORDER BY DevicesFixed DESC  "\
              "LIMIT 1;"

        cursor.execute(sql)

        # Loop through the results
        for (name, count) in cursor:
            print(f"{name} fixed {count} devices")
        print("----------------------------")
    elif choice == 3:
        # Query3: Show the profits generated by each cashier
        print("\n----------------------------")

        sql = "SELECT CONCAT(Employee.FirstName, ' ', Employee.LastName) AS EmployeeName, SUM(Offer.Price - Offer.Cost) AS TotalProfit " \
                "FROM Offer " \
                "JOIN StoreTransaction ON Offer.Id = StoreTransaction.OfferId " \
                "JOIN Employee ON Employee.Id = StoreTransaction.EmployeeId  " \
                "GROUP BY EmployeeName;"

        cursor.execute(sql)

        # Loop through the results
        for (name, profit) in cursor:
            print(f"{name} generated ${profit} in profit")
        print("----------------------------")
    elif choice == 4:
        # Query4: Find the customer who came to the store the most
        print("\n----------------------------")

        sql = "SELECT CONCAT(Customer.FirstName, ' ', Customer.LastName) as FullName, "\
              "COUNT(*) as TimesShopped "\
              "FROM StoreTransaction "\
              "JOIN Customer ON Customer.Id = StoreTransaction.CustomerId "\
              "GROUP BY StoreTransaction.CustomerId "\
              "ORDER BY TimesShopped DESC "\
              "LIMIT 1;"

        cursor.execute(sql)

        # Loop through the results
        for (name, count) in cursor:
            print(f"{name} came to the store {count} times")
        print("----------------------------")
    elif choice == 5:
        # Query5: Find the total profit on October 1, 2022
        print("\n----------------------------")

        sql = "SELECT SUM(o.Price - o.Cost) AS TotalProfit "\
            "FROM Offer o "\
            "JOIN StoreTransaction t ON t.OfferId = o.Id "\
            "WHERE t.Day = 1 AND t.Month = 10 AND t.Year = 2022;"


        cursor.execute(sql)

        # Loop through the results
        for (profit,) in cursor:
            print(f"Total profit on October 1, 2022: ${profit}")
        print("----------------------------")
    elif choice == 6:
        # Query6: Find the total number of customers who shopped in October
        print("\n----------------------------")

        sql = "SELECT COUNT(DISTINCT CustomerId) AS 'Total Customers This Month' "\
              "FROM StoreTransaction "\
              "WHERE Month = 10;"

        cursor.execute(sql)

        # Loop through the results
        for (count,) in cursor:
            print(f"Total customers who shopped in October: {count}")
    elif choice == 7:
        # Query7: Find the most expensive product
        print("\n----------------------------")

        sql = "SELECT Name, Price "\
              "FROM Offer "\
              "WHERE Price = (SELECT MAX(Price) FROM Offer);"

        cursor.execute(sql)

        # Loop through the results
        for (name, price) in cursor:
            print(f"Most expensive product: {name} (${price})")
        print("----------------------------")
    elif choice == 8:
        # Query8: Find the employees who don't fix devices
        print("\n----------------------------")

        sql = "SELECT CONCAT(e.FirstName, ' ', e.LastName) AS 'Employees That Never Did a Service Task' "\
              "FROM Employee e "\
              "LEFT JOIN EmployeeDoesService eds ON eds.EmployeeId = e.Id "\
              "WHERE eds.EmployeeId IS NULL;"

        cursor.execute(sql)

        # Loop through the results
        for (name,) in cursor:
            print(name)
        print("----------------------------")
    elif choice == 9:
        # Query9: Find the customers with an email address
        print("\n----------------------------")

        sql = "SELECT CONCAT(FirstName, ' ', LastName) AS FullName, Email "\
              "FROM Customer "\
              "WHERE Email IS NOT NULL;"

        cursor.execute(sql)

        # Loop through the results
        for (name, email) in cursor:
            print(f"{name}: {email}")
        print("----------------------------")
    elif choice == 10:
        # Query10: Find all iPhone products and services
        print("\n----------------------------")

        sql = "SELECT * "\
              "FROM Offer "\
              "WHERE Name LIKE '%iPhone%';"

        cursor.execute(sql)

        # Loop through the results
        for row in cursor:
            print(row)
        print("----------------------------")

# Close the database connection
db.close()
# Print a message to indicate that the program has ended
print("\nGoodbye! Thank you for using the Iconic Tech application.")
