CREATE TABLE Offer(
Id INTEGER PRIMARY KEY AUTOINCREMENT,
Name VARCHAR(255) NOT NULL,
Price INTEGER NOT NULL,
Cost INTEGER NOT NULL
);

CREATE TABLE Service(
Id INTEGER PRIMARY KEY AUTOINCREMENT,
ServiceNumber INTEGER NOT NULL,
Status VARCHAR(255) NOT NULL,
OfferId INTEGER NOT NULL,
CONSTRAINT ServiceNumber UNIQUE(ServiceNumber),
CONSTRAINT FK_OfferId FOREIGN KEY(OfferId) REFERENCES Offer(Id)
);

CREATE TABLE Product(
Id INTEGER PRIMARY KEY AUTOINCREMENT,
SerialNumber VARCHAR(255) NOT NULL,
Availability VARCHAR(255) NOT NULL,
OfferId INTEGER NOT NULL,
CONSTRAINT UK_SerialNumber UNIQUE(SerialNumber),
CONSTRAINT FK_OfferId FOREIGN KEY(OfferId) REFERENCES Offer(Id)
);

CREATE TABLE StoreTransaction(
Id INTEGER PRIMARY KEY AUTOINCREMENT,
RecieptNumber INTEGER NOT NULL,
PaymentMethod VARCHAR(255) NOT NULL,
Day INTEGER NOT NULL,
Month INTEGER NOT NULL,
Year INTEGER NOT NULL,
CustomerId INTEGER NULL,
EmployeeId INTEGER NOT NULL,
OfferId INTEGER UNIQUE NOT NULL,
CONSTRAINT UK_RecieptNumber UNIQUE(RecieptNumber),
CONSTRAINT FK_CustomerId FOREIGN KEY(CustomerId) REFERENCES Customer(Id),
CONSTRAINT FK_EmployeeId FOREIGN KEY(EmployeeId) REFERENCES Employee(Id),
CONSTRAINT FK_OfferId FOREIGN KEY(OfferId) REFERENCES Offer(Id)
);

CREATE TABLE Employee(
Id INTEGER PRIMARY KEY AUTOINCREMENT,
FirstName VARCHAR(255) NOT NULL,
LastName VARCHAR(255) NOT NULL,
PhoneNumber INTEGER NOT NULL,
CONSTRAINT UK_FirstName_LastName UNIQUE(FirstName, LastName)
);

CREATE TABLE EmployeeDoesService(
Id INTEGER PRIMARY KEY AUTOINCREMENT,
EmployeeId INTEGER NOT NULL,
ServiceId INTEGER UNIQUE NOT NULL,
Day INTEGER NOT NULL,
Month INTEGER NOT NULL,
Year INTEGER NOT NULL, Notes VARCHAR(255) NULL,
CONSTRAINT FK_EmployeeId FOREIGN KEY(EmployeeId) REFERENCES Employee(Id),
CONSTRAINT FK_ServiceId FOREIGN KEY(ServiceId) REFERENCES Service(Id)
);

CREATE TABLE Customer(
Id INTEGER PRIMARY KEY AUTOINCREMENT,
FirstName VARCHAR(255) NOT NULL,
LastName VARCHAR(255) NOT NULL,
PhoneNumber INTEGER NOT NULL,
Email VARCHAR(255) NULL, 
CONSTRAINT UK_FirstName_PhoneNumber UNIQUE(FirstName, PhoneNumber)
);