CREATE TABLE Offer (
  Id INT PRIMARY KEY AUTO_INCREMENT,
  Name VARCHAR(255) NOT NULL,
  Price INT NOT NULL,
  Cost INT NOT NULL
);

CREATE TABLE Service (
  Id INT PRIMARY KEY AUTO_INCREMENT,
  ServiceNumber INT NOT NULL,
  Status VARCHAR(255) NOT NULL,
  OfferId INT NOT NULL,
  UNIQUE(ServiceNumber),
  FOREIGN KEY (OfferId) REFERENCES Offer(Id)
);

CREATE TABLE Product (
  Id INT PRIMARY KEY AUTO_INCREMENT,
  SerialNumber VARCHAR(255) NOT NULL,
  Availability VARCHAR(255) NOT NULL,
  OfferId INT NOT NULL,
  UNIQUE(SerialNumber),
  FOREIGN KEY (OfferId) REFERENCES Offer(Id)
);

CREATE TABLE StoreTransaction(
Id INTEGER PRIMARY KEY AUTO_INCREMENT,
RecieptNumber BIGINT NOT NULL,
PaymentMethod VARCHAR(255) NOT NULL,
Day INTEGER NOT NULL,
Month INTEGER NOT NULL,
Year INTEGER NOT NULL,
CustomerId INTEGER NULL,
EmployeeId INTEGER NOT NULL,
OfferId INTEGER UNIQUE NOT NULL,
CONSTRAINT UK_RecieptNumber UNIQUE(RecieptNumber),
CONSTRAINT FK_CustomerId FOREIGN KEY(CustomerId) REFERENCES Customer(Id),
CONSTRAINT FK_EmployeeId FOREIGN KEY(EmployeeId) REFERENCES Employee(Id),
CONSTRAINT FK_OfferId FOREIGN KEY(OfferId) REFERENCES Offer(Id)
);

CREATE TABLE Employee (
  Id INT PRIMARY KEY AUTO_INCREMENT,
  FirstName VARCHAR(255) NOT NULL,
  LastName VARCHAR(255) NOT NULL,
  PhoneNumber BIGINT NOT NULL,
  UNIQUE(FirstName, LastName)
);

CREATE TABLE EmployeeDoesService (
  Id INT PRIMARY KEY AUTO_INCREMENT,
  EmployeeId INT NOT NULL,
  ServiceId INT UNIQUE NOT NULL,
  Day INT NOT NULL,
  Month INT NOT NULL,
  Year INT NOT NULL,
  Notes VARCHAR(255),
  FOREIGN KEY (EmployeeId) REFERENCES Employee(Id),
  FOREIGN KEY (ServiceId) REFERENCES Service(Id)
);

CREATE TABLE Customer (
  Id INT PRIMARY KEY AUTO_INCREMENT,
  FirstName VARCHAR(255) NOT NULL,
  LastName VARCHAR(255) NOT NULL,
  PhoneNumber BIGINT NOT NULL,
  Email VARCHAR(255),
  UNIQUE(FirstName, PhoneNumber)
);